spring.application.name=authservice

spring.datasource.url=jdbc:postgresql://localhost:5436/auth_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=3600000

server.port=8080

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.docker.compose.enabled=false

# Super Admin seed (sobreescribible por variables de entorno)
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.organization-id=${ADMIN_ORG_ID:a81476a6-7acc-4740-b254-1ce685d17762}
admin.person-id=${ADMIN_PERSON_ID:b92587b7-8bdd-4851-c365-2df796e28873}

# Titular de prueba (END_USER) seed
titular.email=${TITULAR_EMAIL}
titular.password=${TITULAR_PASSWORD}
titular.person-id=${TITULAR_PERSON_ID:c83698c8-9cff-4862-b476-3ef907f29984}

#Cosas para el correo electronico
spring.mail.host=smtp.gmail.com
spring.mail.port= 587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true