spring.application.name=authservice

spring.datasource.url=jdbc:postgresql://localhost:5436/auth_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

application.security.jwt.secret-key=${JWT_SECRET:3d8f2b4e6a9c1f0e7b5d3a2c4f8e6b1d3a9f2e5c7b0d4a6e8f1c3b5d7a9e2f4}
application.security.jwt.expiration=3600000

server.port=8080

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.docker.compose.enabled=false

# Super Admin seed (sobreescribible por variables de entorno)
admin.email=${ADMIN_EMAIL:admin@privdata.cl}
admin.password=${ADMIN_PASSWORD:Admin1234!}
admin.organization-id=${ADMIN_ORG_ID:a81476a6-7acc-4740-b254-1ce685d17762}
admin.person-id=${ADMIN_PERSON_ID:b92587b7-8bdd-4851-c365-2df796e28873}

# Titular de prueba (END_USER) seed
titular.email=${TITULAR_EMAIL:titular@privdata.cl}
titular.password=${TITULAR_PASSWORD:Titular1234!}
titular.person-id=${TITULAR_PERSON_ID:c83698c8-9cff-4862-b476-3ef907f29984}

# Auditor de la Agencia de prueba (AGENCY_AUDITOR) seed
agency-auditor.email=${AGENCY_AUDITOR_EMAIL:auditor@agencia.cl}
agency-auditor.password=${AGENCY_AUDITOR_PASSWORD:Auditor1234!}
agency-auditor.person-id=${AGENCY_AUDITOR_PERSON_ID:85795030-53f8-4575-9716-706a14bdc94c}

#Cosas para el correo electronico
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:false}