spring.application.name=bff-api

services.auth.url=${SERVICES_AUTH_URL:http://localhost:8080}
server.port=${SERVER_PORT:8085}
services.organization.url=http://localhost:8081
services.arco.url=http://localhost:8082
services.rat.url=http://localhost:8083

# React frontend
frontend.url=http://localhost:5173

spring.docker.compose.enabled=false
