spring.application.name=bff-api

server.port=${SERVER_PORT:8085}

services.auth.url=${SERVICES_AUTH_URL:http://localhost:8080}
services.organization.url=${SERVICES_ORGANIZATION_URL:http://localhost:8081}
services.arco.url=${SERVICES_ARCO_URL:http://localhost:8082}
services.compliance.url=${SERVICES_COMPLIANCE_URL:http://localhost:8083}
services.agencia.url=${SERVICES_AGENCIA_URL:http://localhost:8084}

frontend.url=${FRONTEND_URL:http://localhost:5173}

spring.docker.compose.enabled=false