services:
  postgres-auth:
    image: postgres:16
    container_name: privdata-postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
      - ./authservice-PrivData/docker/init:/docker-entrypoint-initdb.d

  postgres-organization:
    image: postgres:16
    container_name: privdata-postgres-organization
    environment:
      POSTGRES_DB: organization_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_organization_data:/var/lib/postgresql/data

  postgres-arco:
    image: postgres:16
    container_name: privdata-postgres-arco
    environment:
      POSTGRES_DB: arco_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - postgres_arco_data:/var/lib/postgresql/data

  auth-service:
    build: ./authservice-PrivData
    container_name: privdata-auth-service
    depends_on:
      - postgres-auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"

  organization-service:
    build: ./organizationService
    container_name: privdata-organization-service
    depends_on:
      - postgres-organization
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-organization:5432/organization_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8081:8081"

  arco-service:
    build: ./Arco-service
    container_name: privdata-arco-service
    depends_on:
      - postgres-arco
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-arco:5432/arco_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8082:8082"

  bff-api:
    build: ./bff-api
    container_name: privdata-bff-api
    depends_on:
      - auth-service
      - organization-service
      - arco-service
    environment:
      SERVER_PORT: 8085
      SERVICES_AUTH_URL: http://auth-service:8080
      SERVICES_ORGANIZATION_URL: http://organization-service:8081
      SERVICES_ARCO_URL: http://arco-service:8082
      SERVICES_COMPLIANCE_URL: http://compliance-service:8083
      FRONTEND_URL: http://localhost:5173
    ports:
      - "8085:8085"

  frontend:
    build: ./frontend-Privdata-main
    container_name: privdata-frontend
    ports:
      - "5173:80"
    depends_on:
      - bff-api

volumes:
  postgres_auth_data:
  postgres_organization_data:
  postgres_arco_data: