spring.application.name=api-gateway
server.port=8000

# JWT
spring.security.oauth2.resourceserver.jwt.secret-key=${JWT_SECRET:privdata-secret-key-privdata-secret-key-privdata}

# Routes
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://auth-service:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=bff-api
spring.cloud.gateway.server.webflux.routes[1].uri=http://bff-api:8085
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/**
management.endpoints.web.exposure.include=health,info,gateway

jwt.secret=${JWT_SECRET:privdata-secret-key-privdata-secret-key-privdata}
