spring.application.name=demo

# Nombre del microservicio
# Puerto del servicio
server.port=8082

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/arco_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logs SQL para desarrollo
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Evitar conflicto con Docker Compose si no lo usas
spring.docker.compose.enabled=false

services.organization.url=${SERVICES_ORGANIZATION_URL:http://organization-service:8081}
services.agencia.url=${SERVICES_AGENCIA_URL:http://localhost:8084}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true