package com.example.demo.enums.arcoRequest;

public enum ArcoStatus {
    RECIBIDA,
    EN_REVISION,
    IDENTIDAD_PENDIENTE,
    IDENTIDAD_VERIFICADA,
    IDENTIDAD_RECHAZADA,
    EN_GESTION,
    RESPONDIDA,
    RECHAZADA,
    PENDIENTE_RECLAMO_AGENCIA,
    RECLAMADA_AGENCIA,
    CERRADA

}
